server:
  port: 8121
spring:
  application:
    name: shiro-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.30.6:3306/shiro_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet.enabled: true
      stat-view-servlet.url-pattern: /druid/*
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 1000
      filter.stat.merge-sql: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # \u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u5206\u9694
  typeAliasesPackage: com.xlkh.shiro.demo.entity
  global-config:
    #\u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E", INPUT:"\u7528\u6237\u8F93\u5165ID", ID_WORKER:"\u5168\u5C40\u552F\u4E00ID(\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: ID_WORKER
      #db-type: mysql
  #\u539F\u751F\u914D\u7F6E
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
